version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "innolab-graalvm-interest-rate-lambda-demo-jvm"
s3_bucket = "innolab-graalvm-bucket"
s3_prefix = "interest-rate-lambda-demo-jvm"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
